package main
func dealWith(err error) {
	if err != nil {
		panic(err)
	}
}